apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: ConfigMap
      name: ultimate-template-api-config
    path: patch-api-config.yaml
  - target:
      kind: ConfigMap
      name: ultimate-template-web-config
    path: patch-web-config.yaml
  - target:
      kind: Ingress
      name: ultimate-template
    path: patch-ingress.yaml
