apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zeeus-assessment
spec:
  tls:
    - hosts:
        - staging-app.example.com
        - staging-api.example.com
      secretName: zeeus-assessment-staging-tls
  rules:
    - host: staging-app.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeeus-assessment-web
                port:
                  number: 3000
    - host: staging-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zeeus-assessment-api
                port:
                  number: 4000

