apiVersion: v1
kind: ConfigMap
metadata:
  name: zeeus-assessment-web-config
data:
  NODE_ENV: 'production'
  APP_ENV: 'production'
  APP_URL: 'https://app.example.com'
  API_ORIGIN: 'http://zeeus-assessment-api:4000'
  WEB_PORT: '3000'
  CSP_REPORT_ONLY: 'false'
  CSP_REPORT_URI: ''
