apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ultimate-template
resources:
  - namespace.yaml
  - configmap-api.yaml
  - configmap-web.yaml
  - secret-example.yaml
  - deployment-api.yaml
  - deployment-web.yaml
  - service-api.yaml
  - service-web.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - hpa-api.yaml
  - hpa-web.yaml
  - pdb-api.yaml
  - pdb-web.yaml
  - migrate-job.yaml
