apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zeeus-assessment-api
spec:
  podSelector:
    matchLabels:
      app: zeeus-assessment-api
  policyTypes: ['Ingress', 'Egress']
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: zeeus-assessment-web
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: zeeus-assessment-web
spec:
  podSelector:
    matchLabels:
      app: zeeus-assessment-web
  policyTypes: ['Ingress', 'Egress']
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: zeeus-assessment-api
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
